/* Main.ino file generated by New Project wizard
 *
 * Created:   %%DATE%%
 * Processor: %%CONTROLLER%%
 * Compiler:  %%COMPILER%%
 */

%%CONFIG_COMMENT%%
%%CONFIG_BEGIN%%
%%CONFIG_END%%

void setup () {
%%PERIPHERAL_SETUP%%
// TODO: put your setup code here, to run once:
}

void loop() {
%%PERIPHERAL_LOOP%%
// TODO: put your main code here, to run repeatedly:
}
