/* Main.c file generated by New Project wizard
 *
 * Created:   %%DATE%%
 * Processor: %%CONTROLLER%%
 * Compiler:  %%COMPILER%%
 */

#include <system.h>

void main()
 { 

   // Write your code here

   while( 1 )
      ;
 }
