/* Main.c file generated by New Project wizard
 *
 * Created:   %%DATE%%
 * Processor: %%CONTROLLER%%
 * Compiler:  %%COMPILER%%
 *
 * Before starting simulation set Internal Memory Size 
 * in the 8086 model properties to 0x10000
 */

void main(void)
 {
   // Write your code here
   while (1)
      ;
 }