/* Main.c file generated by New Project wizard
 *
 * Created:   %%DATE%%
 * Processor: %%CONTROLLER%%
 * Compiler:  %%COMPILER%%
 */

#include <%%INCFILE%%>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
