# !/usr/bin/env python3

#!/usr/bin/env python3

# Main.py file generated by New Project wizard

# Created:   %%DATE%%
# Processor: %%CONTROLLER%%
# Compiler:  %%COMPILER%%

# Modules
from goto import *
import time
import var
import pio
import resource

%%CONFIG_COMMENT%%
%%CONFIG_BEGIN%%
%%CONFIG_END%%

# Main function
def main () :
# Setup
 %%PERIPHERAL_SETUP%%
# Infinite loop
 while 1 :
  %%PERIPHERAL_LOOP%%
  pass
# Command line execution
if __name__ == '__main__' :
   main()
