;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   %%DATE%%
; Processor: %%CONTROLLER%%
; Compiler:  %%COMPILER%%
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
        ; Write your code here
ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START