' ====================================================================
' Main.bas file generated by New Project wizard
'
' Created:   %%DATE%%
' Processor: %%CONTROLLER%%
' Compiler:  %%COMPILER%%
' ====================================================================


main:	
	' Write your code here
	goto main

