/* Main.c file generated by New Project wizard
 *
 * Created:   %%DATE%%
 * Processor: %%CONTROLLER%%
 * Compiler:  %%COMPILER%%
 */

#include <mcs51reg.h>

void main(void)
 { 
   // Write your code here
   while (1)
      ;
 }